.TH INTERNSCTL 1 "Date" "v0.1.0" "internsctl manual"
.SH NAME
internsctl \- custom command for operations
.SH SYNOPSIS
.B internsctl
[OPTION]...
.SH DESCRIPTION
Custom command for various operations.
.SH OPTIONS
.TP
.B --help
Display help.
.TP
.B --version
Display version information.
.SH AUTHOR
Written by [Pankaj Adiley].
